2025-03-11 13:39:55,505 INFO    StreamThr :15092 [internal.py:wandb_internal():86] W&B internal server running at pid: 15092, started at: 2025-03-11 13:39:55.502333
2025-03-11 13:39:55,524 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status
2025-03-11 13:39:55,667 INFO    WriterThread:15092 [datastore.py:open_for_write():85] open: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\run-bogwj9ww.wandb
2025-03-11 13:39:55,673 DEBUG   SenderThread:15092 [sender.py:send():382] send: header
2025-03-11 13:39:55,805 DEBUG   SenderThread:15092 [sender.py:send():382] send: run
2025-03-11 13:39:56,484 INFO    SenderThread:15092 [dir_watcher.py:__init__():211] watching files in: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files
2025-03-11 13:39:56,484 INFO    SenderThread:15092 [sender.py:_start_run_threads():1136] run started: bogwj9ww with start time 1741680595.504327
2025-03-11 13:39:56,525 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: check_version
2025-03-11 13:39:56,526 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: check_version
2025-03-11 13:39:56,682 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: run_start
2025-03-11 13:39:57,865 DEBUG   HandlerThread:15092 [system_info.py:__init__():32] System info init
2025-03-11 13:39:57,865 DEBUG   HandlerThread:15092 [system_info.py:__init__():47] System info init done
2025-03-11 13:39:57,865 INFO    HandlerThread:15092 [system_monitor.py:start():194] Starting system monitor
2025-03-11 13:39:57,866 INFO    SystemMonitor:15092 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-03-11 13:39:57,866 INFO    HandlerThread:15092 [system_monitor.py:probe():214] Collecting system info
2025-03-11 13:39:57,875 INFO    SystemMonitor:15092 [interfaces.py:start():190] Started cpu monitoring
2025-03-11 13:39:57,877 INFO    SystemMonitor:15092 [interfaces.py:start():190] Started disk monitoring
2025-03-11 13:39:57,878 INFO    SystemMonitor:15092 [interfaces.py:start():190] Started gpu monitoring
2025-03-11 13:39:57,895 INFO    SystemMonitor:15092 [interfaces.py:start():190] Started memory monitoring
2025-03-11 13:39:57,904 DEBUG   HandlerThread:15092 [system_info.py:probe():196] Probing system
2025-03-11 13:39:57,939 INFO    SystemMonitor:15092 [interfaces.py:start():190] Started network monitoring
2025-03-11 13:39:57,943 DEBUG   HandlerThread:15092 [system_info.py:_probe_git():181] Probing git
2025-03-11 13:39:58,169 DEBUG   HandlerThread:15092 [system_info.py:_probe_git():189] Probing git done
2025-03-11 13:39:58,169 DEBUG   HandlerThread:15092 [system_info.py:probe():244] Probing system done
2025-03-11 13:39:58,169 DEBUG   HandlerThread:15092 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.26100-SP0', 'python': '3.9.5', 'heartbeatAt': '2025-03-11T08:09:57.938590', 'startedAt': '2025-03-11T08:09:55.435102', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'git@github.com-work:saimanikumar-da24m016/da6401_assignment1.git', 'commit': 'e828d7ed826d245b35090fa330e5d4f07dddcfac'}, 'email': 'saimanikumar67@gmail.com', 'root': 'C:/Users/D. Sai Mani Kumar/Downloads/DL/da6401_assignment1', 'host': 'LAPTOP-VRI27UL2', 'username': 'D. Sai Mani Kumar', 'executable': 'c:\\Users\\D. Sai Mani Kumar\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 1500.0, 'min': 0.0, 'max': 2400.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 0.0, 'max': 2400.0}], 'disk': {'/': {'total': 375.82519149780273, 'used': 276.4979019165039}}, 'gpu': 'NVIDIA GeForce GTX 1650 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1650 Ti', 'memory_total': 4294967296}], 'memory': {'total': 7.840869903564453}}
2025-03-11 13:39:58,169 INFO    HandlerThread:15092 [system_monitor.py:probe():224] Finished collecting system info
2025-03-11 13:39:58,170 INFO    HandlerThread:15092 [system_monitor.py:probe():227] Publishing system info
2025-03-11 13:39:58,170 DEBUG   HandlerThread:15092 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2025-03-11 13:39:58,173 DEBUG   HandlerThread:15092 [system_info.py:_save_pip():68] Saving pip packages done
2025-03-11 13:39:58,176 INFO    HandlerThread:15092 [system_monitor.py:probe():229] Finished publishing system info
2025-03-11 13:39:58,212 DEBUG   SenderThread:15092 [sender.py:send():382] send: files
2025-03-11 13:39:58,212 INFO    SenderThread:15092 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2025-03-11 13:39:58,274 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:39:58,275 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:39:58,280 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:39:58,506 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\wandb-metadata.json
2025-03-11 13:39:58,508 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\requirements.txt
2025-03-11 13:39:58,608 DEBUG   SenderThread:15092 [sender.py:send():382] send: telemetry
2025-03-11 13:39:58,608 DEBUG   SenderThread:15092 [sender.py:send():382] send: telemetry
2025-03-11 13:39:58,610 DEBUG   SenderThread:15092 [sender.py:send():382] send: run
2025-03-11 13:39:58,934 INFO    SenderThread:15092 [sender.py:send_run():1010] updated run: bogwj9ww
2025-03-11 13:39:59,255 INFO    wandb-upload_0:15092 [upload_job.py:push():131] Uploaded file C:\Users\D9110~1.SAI\AppData\Local\Temp\tmpdfymkyjdwandb\qsnsjilz-wandb-metadata.json
2025-03-11 13:39:59,501 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\config.yaml
2025-03-11 13:39:59,502 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\output.log
2025-03-11 13:40:00,015 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:00,016 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:00,963 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:40:01,527 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\output.log
2025-03-11 13:40:02,465 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:02,465 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:04,890 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:04,890 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:06,006 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:40:07,297 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:07,297 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:07,449 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:40:07,453 DEBUG   SenderThread:15092 [sender.py:send():382] send: history
2025-03-11 13:40:07,455 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:40:07,461 INFO    SenderThread:15092 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:40:07,577 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\wandb-summary.json
2025-03-11 13:40:09,606 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\output.log
2025-03-11 13:40:09,728 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:09,729 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:11,492 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:40:12,166 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:12,166 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:13,273 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:40:13,274 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:40:13,289 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:40:14,579 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:14,580 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:15,729 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:40:15,731 DEBUG   SenderThread:15092 [sender.py:send():382] send: history
2025-03-11 13:40:15,731 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:40:15,737 INFO    SenderThread:15092 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:40:16,678 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\wandb-summary.json
2025-03-11 13:40:16,755 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:40:17,006 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:17,007 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:17,689 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\output.log
2025-03-11 13:40:19,439 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:19,440 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:21,806 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:40:21,853 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:21,856 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:24,343 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:24,344 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:25,248 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:40:25,250 DEBUG   SenderThread:15092 [sender.py:send():382] send: history
2025-03-11 13:40:25,250 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:40:25,255 INFO    SenderThread:15092 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:40:25,782 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\wandb-summary.json
2025-03-11 13:40:26,767 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:26,767 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:27,284 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:40:27,803 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\output.log
2025-03-11 13:40:27,804 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\config.yaml
2025-03-11 13:40:28,284 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:40:28,285 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:40:28,301 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:40:29,197 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:29,197 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:31,620 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:31,622 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:32,788 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:40:36,194 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:36,195 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:36,801 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:40:36,803 DEBUG   SenderThread:15092 [sender.py:send():382] send: history
2025-03-11 13:40:36,804 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:40:36,807 INFO    SenderThread:15092 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:40:37,250 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\wandb-summary.json
2025-03-11 13:40:37,822 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:40:38,658 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:38,658 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:40:39,299 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\output.log
2025-03-12 01:40:39,235 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-12 01:40:40,912 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-12 01:40:41,548 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: stop_status
2025-03-12 01:40:41,550 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: stop_status
2025-03-12 01:40:41,562 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-12 01:40:46,686 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: keepalive
2025-03-12 01:40:48,934 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-12 01:40:51,858 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: keepalive
2025-03-12 01:40:54,979 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: partial_history
2025-03-12 01:40:55,136 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: partial_history
2025-03-12 01:40:56,173 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-12 01:40:56,201 DEBUG   SystemMonitor:15092 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-03-12 01:40:56,722 WARNING FileStreamThread:15092 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000024320A2DFD0>>, timeout=180), args: ('https://api.wandb.ai/files/da24m016-indian-institute-of-technology-madras/DL_Assignment_01/bogwj9ww/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"epoch": 4, "loss": 0.44457785451525966, "accuracy": 0.8436111111111111, "val_loss": 0.44151889180929516, "val_accuracy": 0.8436666666666667, "_timestamp": 1741680636.801425, "_runtime": 41.29709792137146, "_step": 3}']}}, 'dropped': 0}}
2025-03-13 15:06:05,992 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-13 15:06:05,992 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-13 15:06:05,993 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-13 15:06:05,993 ERROR   gpu       :15092 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-13 15:06:06,019 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: keepalive
2025-03-13 15:06:10,783 INFO    SenderThread:15092 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000024320B03580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 802, in urlopen
    retries = retries.increment(
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024320B03580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024320B03580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2025-03-13 15:06:11,111 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: keepalive
2025-03-13 15:06:16,614 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: keepalive
2025-03-13 15:06:21,356 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: keepalive
2025-03-13 15:06:26,408 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: keepalive
2025-03-13 15:06:26,754 DEBUG   SenderThread:15092 [sender.py:send():382] send: history
2025-03-13 15:06:26,754 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-13 15:06:26,755 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: summary_record
2025-03-13 15:06:26,769 INFO    SenderThread:15092 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-13 15:06:26,780 DEBUG   SenderThread:15092 [sender.py:send():382] send: history
2025-03-13 15:06:26,780 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: summary_record
2025-03-13 15:06:26,782 INFO    SenderThread:15092 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-13 15:06:26,784 DEBUG   SenderThread:15092 [sender.py:send():382] send: telemetry
2025-03-13 15:06:26,785 DEBUG   SenderThread:15092 [sender.py:send():382] send: exit
2025-03-13 15:06:26,788 INFO    SenderThread:15092 [sender.py:send_exit():589] handling exit code: 0
2025-03-13 15:06:26,820 INFO    SenderThread:15092 [sender.py:send_exit():591] handling runtime: 43258
2025-03-13 15:06:26,823 INFO    SenderThread:15092 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-13 15:06:26,824 INFO    SenderThread:15092 [sender.py:send_exit():597] send defer
2025-03-13 15:06:26,835 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: poll_exit
2025-03-13 15:06:26,835 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:26,856 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 0
2025-03-13 15:06:26,862 DEBUG   SenderThread:15092 [sender.py:send():382] send: stats
2025-03-13 15:06:26,867 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:26,868 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 0
2025-03-13 15:06:26,870 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 1
2025-03-13 15:06:26,871 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:26,871 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 1
2025-03-13 15:06:26,873 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:26,874 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 1
2025-03-13 15:06:26,874 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 2
2025-03-13 15:06:26,874 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:26,874 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 2
2025-03-13 15:06:26,875 INFO    HandlerThread:15092 [system_monitor.py:finish():203] Stopping system monitor
2025-03-13 15:06:26,879 DEBUG   SystemMonitor:15092 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-03-13 15:06:26,900 INFO    HandlerThread:15092 [interfaces.py:finish():202] Joined cpu monitor
2025-03-13 15:06:26,901 DEBUG   SystemMonitor:15092 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-03-13 15:06:26,903 INFO    HandlerThread:15092 [interfaces.py:finish():202] Joined disk monitor
2025-03-13 15:06:27,033 INFO    HandlerThread:15092 [interfaces.py:finish():202] Joined gpu monitor
2025-03-13 15:06:27,034 INFO    HandlerThread:15092 [interfaces.py:finish():202] Joined memory monitor
2025-03-13 15:06:27,035 INFO    HandlerThread:15092 [interfaces.py:finish():202] Joined network monitor
2025-03-13 15:06:27,037 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:27,037 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 2
2025-03-13 15:06:27,037 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 3
2025-03-13 15:06:27,037 DEBUG   SenderThread:15092 [sender.py:send():382] send: stats
2025-03-13 15:06:27,038 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:27,039 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 3
2025-03-13 15:06:27,039 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:27,040 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 3
2025-03-13 15:06:27,040 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 4
2025-03-13 15:06:27,040 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:27,040 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 4
2025-03-13 15:06:27,042 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:27,042 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 4
2025-03-13 15:06:27,043 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 5
2025-03-13 15:06:27,045 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:27,045 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 5
2025-03-13 15:06:27,046 DEBUG   SenderThread:15092 [sender.py:send():382] send: summary
2025-03-13 15:06:27,049 INFO    SenderThread:15092 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-13 15:06:27,051 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:27,051 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 5
2025-03-13 15:06:27,052 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 6
2025-03-13 15:06:27,052 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:27,052 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 6
2025-03-13 15:06:27,054 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:27,055 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 6
2025-03-13 15:06:27,073 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: status_report
2025-03-13 15:06:27,245 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\wandb-summary.json
2025-03-13 15:06:27,426 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-13 15:06:27,702 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 7
2025-03-13 15:06:27,702 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: poll_exit
2025-03-13 15:06:27,704 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:27,704 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 7
2025-03-13 15:06:27,706 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:27,706 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 7
2025-03-13 15:06:28,244 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\config.yaml
2025-03-13 15:06:28,598 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-13 15:06:28,875 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 8
2025-03-13 15:06:28,876 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: poll_exit
2025-03-13 15:06:28,876 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:28,877 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 8
2025-03-13 15:06:28,878 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:28,878 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 8
2025-03-13 15:06:28,879 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 9
2025-03-13 15:06:28,879 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:28,880 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 9
2025-03-13 15:06:28,880 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:28,880 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 9
2025-03-13 15:06:28,881 INFO    SenderThread:15092 [dir_watcher.py:finish():358] shutting down directory watcher
2025-03-13 15:06:29,262 INFO    Thread-16 :15092 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\output.log
2025-03-13 15:06:29,267 INFO    SenderThread:15092 [dir_watcher.py:finish():388] scan: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files
2025-03-13 15:06:29,271 INFO    SenderThread:15092 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\config.yaml config.yaml
2025-03-13 15:06:29,275 INFO    SenderThread:15092 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\output.log output.log
2025-03-13 15:06:29,296 INFO    SenderThread:15092 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\requirements.txt requirements.txt
2025-03-13 15:06:29,302 INFO    SenderThread:15092 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\wandb-metadata.json wandb-metadata.json
2025-03-13 15:06:29,302 INFO    SenderThread:15092 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\wandb-summary.json wandb-summary.json
2025-03-13 15:06:29,331 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 10
2025-03-13 15:06:29,331 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:29,332 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 10
2025-03-13 15:06:29,341 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:29,342 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 10
2025-03-13 15:06:29,342 INFO    SenderThread:15092 [file_pusher.py:finish():175] shutting down file pusher
2025-03-13 15:06:30,280 INFO    wandb-upload_0:15092 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\config.yaml
2025-03-13 15:06:30,357 INFO    wandb-upload_1:15092 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\output.log
2025-03-13 15:06:30,367 INFO    wandb-upload_3:15092 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\wandb-summary.json
2025-03-13 15:06:30,385 WARNING StreamThr :15092 [internal.py:is_dead():414] Internal process exiting, parent pid 5828 disappeared
2025-03-13 15:06:30,386 ERROR   StreamThr :15092 [internal.py:wandb_internal():152] Internal process shutdown.
2025-03-13 15:06:30,524 INFO    wandb-upload_2:15092 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\files\requirements.txt
2025-03-13 15:06:30,525 INFO    MainThread:15092 [internal.py:handle_exit():76] Internal process exited
2025-03-13 15:06:30,731 INFO    Thread-15 :15092 [sender.py:transition_state():617] send defer: 11
2025-03-13 15:06:30,732 DEBUG   HandlerThread:15092 [handler.py:handle_request():146] handle_request: defer
2025-03-13 15:06:30,732 INFO    HandlerThread:15092 [handler.py:handle_request_defer():172] handle defer: 11
2025-03-13 15:06:30,732 INFO    HandlerThread:15092 [handler.py:finish():866] shutting down handler
2025-03-13 15:06:30,733 INFO    WriterThread:15092 [datastore.py:close():294] close: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133955-bogwj9ww\run-bogwj9ww.wandb
2025-03-13 15:06:30,734 DEBUG   SenderThread:15092 [sender.py:send_request():409] send_request: defer
2025-03-13 15:06:30,734 INFO    SenderThread:15092 [sender.py:send_request_defer():613] handle sender defer: 11
2025-03-13 15:06:30,736 INFO    SenderThread:15092 [file_pusher.py:join():181] waiting for file pusher
2025-03-13 15:06:30,736 INFO    SenderThread:15092 [sender.py:transition_state():617] send defer: 12
2025-03-13 15:06:30,736 INFO    SenderThread:15092 [sender.py:finish():1548] shutting down sender
2025-03-13 15:06:30,736 INFO    SenderThread:15092 [file_pusher.py:finish():175] shutting down file pusher
2025-03-13 15:06:30,736 INFO    SenderThread:15092 [file_pusher.py:join():181] waiting for file pusher
2025-03-13 15:06:30,743 INFO    SenderThread:15092 [file_stream.py:finish():595] file stream finish called
