2025-03-17 00:35:00,217 INFO    StreamThr :30328 [internal.py:wandb_internal():86] W&B internal server running at pid: 30328, started at: 2025-03-17 00:35:00.151187
2025-03-17 00:35:00,267 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status
2025-03-17 00:35:00,423 INFO    WriterThread:30328 [datastore.py:open_for_write():85] open: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\run-qh0l59uo.wandb
2025-03-17 00:35:00,426 DEBUG   SenderThread:30328 [sender.py:send():382] send: header
2025-03-17 00:35:00,728 DEBUG   SenderThread:30328 [sender.py:send():382] send: run
2025-03-17 00:35:01,463 INFO    SenderThread:30328 [dir_watcher.py:__init__():211] watching files in: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files
2025-03-17 00:35:01,464 INFO    SenderThread:30328 [sender.py:_start_run_threads():1136] run started: qh0l59uo with start time 1742151900.19718
2025-03-17 00:35:01,507 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: check_version
2025-03-17 00:35:01,508 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: check_version
2025-03-17 00:35:01,652 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: run_start
2025-03-17 00:35:01,724 DEBUG   HandlerThread:30328 [system_info.py:__init__():32] System info init
2025-03-17 00:35:01,724 DEBUG   HandlerThread:30328 [system_info.py:__init__():47] System info init done
2025-03-17 00:35:01,725 INFO    HandlerThread:30328 [system_monitor.py:start():194] Starting system monitor
2025-03-17 00:35:01,725 INFO    SystemMonitor:30328 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-03-17 00:35:01,725 INFO    HandlerThread:30328 [system_monitor.py:probe():214] Collecting system info
2025-03-17 00:35:01,774 INFO    SystemMonitor:30328 [interfaces.py:start():190] Started cpu monitoring
2025-03-17 00:35:01,780 INFO    SystemMonitor:30328 [interfaces.py:start():190] Started disk monitoring
2025-03-17 00:35:01,791 INFO    SystemMonitor:30328 [interfaces.py:start():190] Started gpu monitoring
2025-03-17 00:35:01,804 DEBUG   HandlerThread:30328 [system_info.py:probe():196] Probing system
2025-03-17 00:35:01,818 INFO    SystemMonitor:30328 [interfaces.py:start():190] Started memory monitoring
2025-03-17 00:35:01,819 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:01,835 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:01,835 INFO    SystemMonitor:30328 [interfaces.py:start():190] Started network monitoring
2025-03-17 00:35:01,849 DEBUG   HandlerThread:30328 [system_info.py:_probe_git():181] Probing git
2025-03-17 00:35:02,008 DEBUG   HandlerThread:30328 [system_info.py:_probe_git():189] Probing git done
2025-03-17 00:35:02,008 DEBUG   HandlerThread:30328 [system_info.py:probe():244] Probing system done
2025-03-17 00:35:02,009 DEBUG   HandlerThread:30328 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.26100-SP0', 'python': '3.9.5', 'heartbeatAt': '2025-03-16T19:05:01.804277', 'startedAt': '2025-03-16T19:04:59.783666', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'git@github.com-work:saimanikumar-da24m016/da6401_assignment1.git', 'commit': 'e828d7ed826d245b35090fa330e5d4f07dddcfac'}, 'email': 'saimanikumar67@gmail.com', 'root': 'C:/Users/D. Sai Mani Kumar/Downloads/DL/da6401_assignment1', 'host': 'LAPTOP-VRI27UL2', 'username': 'D. Sai Mani Kumar', 'executable': 'c:\\Users\\D. Sai Mani Kumar\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2400.0, 'min': 0.0, 'max': 2400.0}, 'cpu_freq_per_core': [{'current': 2400.0, 'min': 0.0, 'max': 2400.0}], 'disk': {'/': {'total': 375.82519149780273, 'used': 272.37410736083984}}, 'gpu': 'NVIDIA GeForce GTX 1650 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1650 Ti', 'memory_total': 4294967296}], 'memory': {'total': 7.840869903564453}}
2025-03-17 00:35:02,009 INFO    HandlerThread:30328 [system_monitor.py:probe():224] Finished collecting system info
2025-03-17 00:35:02,009 INFO    HandlerThread:30328 [system_monitor.py:probe():227] Publishing system info
2025-03-17 00:35:02,009 DEBUG   HandlerThread:30328 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2025-03-17 00:35:02,015 DEBUG   HandlerThread:30328 [system_info.py:_save_pip():68] Saving pip packages done
2025-03-17 00:35:02,018 INFO    HandlerThread:30328 [system_monitor.py:probe():229] Finished publishing system info
2025-03-17 00:35:02,019 DEBUG   SenderThread:30328 [sender.py:send():382] send: files
2025-03-17 00:35:02,019 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2025-03-17 00:35:02,084 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:35:02,086 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:35:02,101 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:35:02,467 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\requirements.txt
2025-03-17 00:35:02,468 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-metadata.json
2025-03-17 00:35:02,508 DEBUG   SenderThread:30328 [sender.py:send():382] send: telemetry
2025-03-17 00:35:02,515 DEBUG   SenderThread:30328 [sender.py:send():382] send: telemetry
2025-03-17 00:35:02,515 DEBUG   SenderThread:30328 [sender.py:send():382] send: config
2025-03-17 00:35:02,515 DEBUG   SenderThread:30328 [sender.py:send():382] send: config
2025-03-17 00:35:02,515 DEBUG   SenderThread:30328 [sender.py:send():382] send: config
2025-03-17 00:35:02,516 DEBUG   SenderThread:30328 [sender.py:send():382] send: config
2025-03-17 00:35:02,516 DEBUG   SenderThread:30328 [sender.py:send():382] send: config
2025-03-17 00:35:02,516 DEBUG   SenderThread:30328 [sender.py:send():382] send: config
2025-03-17 00:35:02,516 DEBUG   SenderThread:30328 [sender.py:send():382] send: config
2025-03-17 00:35:02,516 DEBUG   SenderThread:30328 [sender.py:send():382] send: config
2025-03-17 00:35:02,516 DEBUG   SenderThread:30328 [sender.py:send():382] send: config
2025-03-17 00:35:03,143 INFO    wandb-upload_0:30328 [upload_job.py:push():131] Uploaded file C:\Users\D9110~1.SAI\AppData\Local\Temp\tmpsxsqc1vswandb\7phzrr09-wandb-metadata.json
2025-03-17 00:35:03,471 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:35:04,773 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:04,774 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:05,554 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:35:05,572 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:35:07,194 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:07,197 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:09,643 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:09,644 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:10,620 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:35:12,073 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:12,075 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:14,485 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:14,485 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:15,652 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:35:16,897 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:16,898 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:17,103 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:35:17,111 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:35:17,137 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:35:19,326 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:19,327 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:21,437 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:35:21,721 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:21,722 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:24,125 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:24,126 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:25,336 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:35:25,340 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:35:25,340 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:35:25,343 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:35:25,746 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:35:26,517 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:26,517 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:27,363 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:35:27,758 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:35:28,925 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:28,926 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:31,318 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:31,319 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:32,123 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:35:32,123 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:35:32,153 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:35:32,557 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:35:33,749 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:33,750 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:33,797 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\config.yaml
2025-03-17 00:35:36,155 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:36,156 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:37,902 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:35:41,134 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:41,135 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:42,947 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:35:43,588 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:43,589 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:46,029 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:46,030 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:47,131 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:35:47,132 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:35:47,161 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:35:48,453 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:48,453 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:48,469 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:35:48,566 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:35:48,567 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:35:48,567 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:35:48,571 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:35:49,140 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:35:50,153 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:35:50,859 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:50,859 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:53,254 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:53,255 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:53,618 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:35:55,644 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:55,645 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:58,076 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:58,077 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:35:58,645 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:00,478 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:00,479 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:01,848 DEBUG   SystemMonitor:30328 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-03-17 00:36:01,850 DEBUG   SenderThread:30328 [sender.py:send():382] send: stats
2025-03-17 00:36:02,160 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:36:02,161 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:36:02,176 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:36:02,865 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:02,865 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:04,523 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:05,284 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:05,284 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:06,998 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:36:06,998 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:36:06,998 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:36:06,999 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:36:07,597 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:36:07,597 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:36:07,681 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:07,681 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:10,030 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:10,093 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:10,094 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:12,531 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:12,532 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:15,062 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:17,170 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:36:17,172 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:36:17,173 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:36:17,464 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:17,464 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:19,869 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:19,869 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:20,560 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:22,264 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:22,265 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:24,659 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:24,660 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:25,602 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:27,069 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:27,070 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:29,397 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:36:29,400 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:36:29,400 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:36:29,403 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:36:29,505 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:29,506 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:30,048 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:36:30,049 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:36:31,411 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:31,865 DEBUG   SenderThread:30328 [sender.py:send():382] send: stats
2025-03-17 00:36:31,945 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:31,946 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:32,163 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:36:32,165 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:36:32,184 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:36:34,381 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:34,382 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:36,500 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:36,817 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:36,818 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:39,222 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:39,222 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:41,534 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:41,612 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:41,613 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:44,006 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:44,007 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:46,481 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:46,481 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:46,567 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:47,181 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:36:47,182 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:36:47,197 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:36:48,888 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:48,889 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:50,218 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:36:50,218 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:36:50,219 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:36:50,220 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:36:50,597 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:36:52,233 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:52,653 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:36:53,870 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:53,871 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:56,272 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:56,273 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:57,265 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:36:58,751 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:36:58,752 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:01,187 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:01,187 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:01,858 DEBUG   SenderThread:30328 [sender.py:send():382] send: stats
2025-03-17 00:37:02,189 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:37:02,190 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:37:02,204 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:37:02,561 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:03,588 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:03,588 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:05,974 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:05,974 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:07,595 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:08,368 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:08,368 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:10,761 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:10,761 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:11,097 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:37:11,098 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:37:11,098 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:37:11,099 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:37:11,926 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:37:12,945 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:37:13,129 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:13,160 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:13,161 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:15,556 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:15,557 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:17,194 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:37:17,195 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:37:17,211 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:37:17,944 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:17,944 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:18,512 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:20,353 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:20,354 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:22,746 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:22,746 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:23,550 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:25,136 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:25,137 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:28,571 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:30,065 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:30,066 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:31,867 DEBUG   SenderThread:30328 [sender.py:send():382] send: stats
2025-03-17 00:37:32,212 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:37:32,213 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:37:32,228 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:37:32,476 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:32,476 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:34,550 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:34,896 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:34,896 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:36,327 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:37:36,328 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:37:36,328 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:37:36,329 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:37:36,330 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:37:37,289 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:37,289 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:38,378 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:37:39,704 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:39,704 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:40,426 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:42,092 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:42,093 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:44,493 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:44,493 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:45,471 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:46,905 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:46,906 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:47,235 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:37:47,236 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:37:47,236 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:37:49,298 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:49,298 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:50,634 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:51,697 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:51,697 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:54,118 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:54,119 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:55,700 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:37:56,514 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:56,514 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:58,914 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:37:58,914 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:00,728 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:01,306 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:01,307 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:01,879 DEBUG   SenderThread:30328 [sender.py:send():382] send: stats
2025-03-17 00:38:02,244 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:38:02,245 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:38:02,245 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:38:06,279 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:06,281 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:06,580 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:08,708 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:08,710 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:10,103 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:38:10,104 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:38:10,105 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:38:10,106 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:38:11,066 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:38:11,143 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:11,144 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:12,117 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:13,093 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:38:13,564 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:13,565 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:15,979 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:15,979 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:17,165 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:17,260 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:38:17,260 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:38:17,261 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:38:18,372 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:18,372 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:20,769 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:20,769 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:22,627 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:23,183 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:23,184 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:25,571 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:25,571 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:27,664 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:27,965 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:27,965 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:30,389 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:30,389 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:31,887 DEBUG   SenderThread:30328 [sender.py:send():382] send: stats
2025-03-17 00:38:32,266 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:38:32,283 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:38:32,283 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:38:32,788 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:32,788 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:33,641 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:35,186 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:35,186 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:35,641 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:38:35,642 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:38:35,642 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:38:35,643 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:38:36,488 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:38:36,488 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:38:37,592 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:37,593 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:38,659 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:42,490 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:42,491 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:43,706 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:44,892 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:44,893 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:47,279 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:47,280 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:38:47,281 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:47,294 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:38:47,295 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:38:49,677 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:49,713 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:49,713 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:52,117 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:52,117 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:54,517 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:54,518 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:54,722 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:38:56,911 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:56,911 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:59,307 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:59,308 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:38:59,765 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:39:01,709 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:39:01,710 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:39:01,902 DEBUG   SenderThread:30328 [sender.py:send():382] send: stats
2025-03-17 00:39:02,298 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: stop_status
2025-03-17 00:39:02,298 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:39:02,299 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: stop_status
2025-03-17 00:39:04,137 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:39:04,138 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:39:05,647 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:39:05,671 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:39:05,674 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:39:05,676 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:39:05,680 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:39:06,151 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:39:06,603 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:39:06,604 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:39:07,180 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:39:09,031 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:39:09,031 ERROR   gpu       :30328 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-17 00:39:09,274 DEBUG   SenderThread:30328 [sender.py:send():382] send: files
2025-03-17 00:39:09,275 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file media\images\Confusion Matrix_10_2489ef4e88558bd2794f.png with policy now
2025-03-17 00:39:09,277 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: partial_history
2025-03-17 00:39:09,281 DEBUG   SenderThread:30328 [sender.py:send():382] send: history
2025-03-17 00:39:09,282 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: summary_record
2025-03-17 00:39:09,283 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:39:09,585 DEBUG   SenderThread:30328 [sender.py:send():382] send: telemetry
2025-03-17 00:39:09,591 DEBUG   SenderThread:30328 [sender.py:send():382] send: exit
2025-03-17 00:39:09,593 INFO    SenderThread:30328 [sender.py:send_exit():589] handling exit code: 0
2025-03-17 00:39:09,594 INFO    SenderThread:30328 [sender.py:send_exit():591] handling runtime: 247
2025-03-17 00:39:09,596 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:39:09,597 INFO    SenderThread:30328 [sender.py:send_exit():597] send defer
2025-03-17 00:39:09,598 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:09,598 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 0
2025-03-17 00:39:09,599 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:09,599 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 0
2025-03-17 00:39:09,599 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 1
2025-03-17 00:39:09,599 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:09,599 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 1
2025-03-17 00:39:09,600 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:09,600 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 1
2025-03-17 00:39:09,600 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 2
2025-03-17 00:39:09,600 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:09,601 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 2
2025-03-17 00:39:09,601 INFO    HandlerThread:30328 [system_monitor.py:finish():203] Stopping system monitor
2025-03-17 00:39:09,601 DEBUG   SystemMonitor:30328 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-03-17 00:39:09,623 INFO    HandlerThread:30328 [interfaces.py:finish():202] Joined cpu monitor
2025-03-17 00:39:09,624 DEBUG   SystemMonitor:30328 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-03-17 00:39:09,626 INFO    HandlerThread:30328 [interfaces.py:finish():202] Joined disk monitor
2025-03-17 00:39:09,745 INFO    HandlerThread:30328 [interfaces.py:finish():202] Joined gpu monitor
2025-03-17 00:39:09,746 INFO    HandlerThread:30328 [interfaces.py:finish():202] Joined memory monitor
2025-03-17 00:39:09,747 INFO    HandlerThread:30328 [interfaces.py:finish():202] Joined network monitor
2025-03-17 00:39:09,748 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:09,748 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 2
2025-03-17 00:39:09,748 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 3
2025-03-17 00:39:09,748 DEBUG   SenderThread:30328 [sender.py:send():382] send: stats
2025-03-17 00:39:09,748 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:09,749 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 3
2025-03-17 00:39:09,750 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:09,750 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 3
2025-03-17 00:39:09,750 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 4
2025-03-17 00:39:09,750 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:09,750 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 4
2025-03-17 00:39:09,751 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:09,751 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 4
2025-03-17 00:39:09,751 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 5
2025-03-17 00:39:09,751 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:09,751 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 5
2025-03-17 00:39:09,752 DEBUG   SenderThread:30328 [sender.py:send():382] send: summary
2025-03-17 00:39:09,752 INFO    SenderThread:30328 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-17 00:39:09,753 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:09,753 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 5
2025-03-17 00:39:09,753 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 6
2025-03-17 00:39:09,753 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:09,754 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 6
2025-03-17 00:39:09,754 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:09,755 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 6
2025-03-17 00:39:09,761 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: status_report
2025-03-17 00:39:10,044 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 7
2025-03-17 00:39:10,045 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:10,045 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 7
2025-03-17 00:39:10,046 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:10,046 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 7
2025-03-17 00:39:10,214 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\config.yaml
2025-03-17 00:39:10,214 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:39:10,215 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\media\images\Confusion Matrix_10_2489ef4e88558bd2794f.png
2025-03-17 00:39:10,215 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\media\images
2025-03-17 00:39:10,216 INFO    Thread-31 :30328 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\media
2025-03-17 00:39:10,275 INFO    wandb-upload_0:30328 [upload_job.py:push():131] Uploaded file C:\Users\D9110~1.SAI\AppData\Local\Temp\tmpsxsqc1vswandb\2r6ps0j7-media/images/Confusion Matrix_10_2489ef4e88558bd2794f.png
2025-03-17 00:39:10,600 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-17 00:39:11,322 INFO    wandb-upload_0:30328 [upload_job.py:push():131] Uploaded file C:\Users\D9110~1.SAI\AppData\Local\Temp\tmpsxsqc1vswandb\y405o1yu-media/images/Confusion Matrix_10_2489ef4e88558bd2794f.png
2025-03-17 00:39:12,488 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 8
2025-03-17 00:39:12,489 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: poll_exit
2025-03-17 00:39:12,490 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:12,490 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 8
2025-03-17 00:39:12,491 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:12,491 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 8
2025-03-17 00:39:12,492 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 9
2025-03-17 00:39:12,492 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:12,492 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 9
2025-03-17 00:39:12,493 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:12,493 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 9
2025-03-17 00:39:12,493 INFO    SenderThread:30328 [dir_watcher.py:finish():358] shutting down directory watcher
2025-03-17 00:39:12,631 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-17 00:39:13,233 INFO    SenderThread:30328 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:39:13,233 INFO    SenderThread:30328 [dir_watcher.py:finish():388] scan: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files
2025-03-17 00:39:13,234 INFO    SenderThread:30328 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\config.yaml config.yaml
2025-03-17 00:39:13,235 INFO    SenderThread:30328 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log output.log
2025-03-17 00:39:13,239 INFO    SenderThread:30328 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\requirements.txt requirements.txt
2025-03-17 00:39:13,241 INFO    SenderThread:30328 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-metadata.json wandb-metadata.json
2025-03-17 00:39:13,244 INFO    SenderThread:30328 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json wandb-summary.json
2025-03-17 00:39:13,257 INFO    SenderThread:30328 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\media\images\Confusion Matrix_10_2489ef4e88558bd2794f.png media/images/Confusion Matrix_10_2489ef4e88558bd2794f.png
2025-03-17 00:39:13,258 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 10
2025-03-17 00:39:13,258 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: poll_exit
2025-03-17 00:39:13,258 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:13,260 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 10
2025-03-17 00:39:13,261 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:13,261 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 10
2025-03-17 00:39:13,262 INFO    SenderThread:30328 [file_pusher.py:finish():175] shutting down file pusher
2025-03-17 00:39:13,688 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-17 00:39:13,688 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: poll_exit
2025-03-17 00:39:14,111 INFO    wandb-upload_1:30328 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\output.log
2025-03-17 00:39:14,298 INFO    wandb-upload_3:30328 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\wandb-summary.json
2025-03-17 00:39:14,401 INFO    wandb-upload_2:30328 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\requirements.txt
2025-03-17 00:39:14,704 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-17 00:39:14,705 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: poll_exit
2025-03-17 00:39:15,002 INFO    wandb-upload_0:30328 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\files\config.yaml
2025-03-17 00:39:15,218 INFO    Thread-30 :30328 [sender.py:transition_state():617] send defer: 11
2025-03-17 00:39:15,218 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:15,219 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 11
2025-03-17 00:39:15,219 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:15,219 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 11
2025-03-17 00:39:15,219 INFO    SenderThread:30328 [file_pusher.py:join():181] waiting for file pusher
2025-03-17 00:39:15,220 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 12
2025-03-17 00:39:15,220 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:15,220 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 12
2025-03-17 00:39:15,220 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:15,220 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 12
2025-03-17 00:39:15,220 INFO    SenderThread:30328 [file_stream.py:finish():595] file stream finish called
2025-03-17 00:39:15,507 INFO    SenderThread:30328 [file_stream.py:finish():599] file stream finish is done
2025-03-17 00:39:15,507 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 13
2025-03-17 00:39:15,508 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:15,508 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 13
2025-03-17 00:39:15,508 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:15,508 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 13
2025-03-17 00:39:15,508 INFO    SenderThread:30328 [sender.py:transition_state():617] send defer: 14
2025-03-17 00:39:15,508 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: defer
2025-03-17 00:39:15,508 INFO    HandlerThread:30328 [handler.py:handle_request_defer():172] handle defer: 14
2025-03-17 00:39:15,509 DEBUG   SenderThread:30328 [sender.py:send():382] send: final
2025-03-17 00:39:15,509 DEBUG   SenderThread:30328 [sender.py:send():382] send: footer
2025-03-17 00:39:15,509 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: defer
2025-03-17 00:39:15,509 INFO    SenderThread:30328 [sender.py:send_request_defer():613] handle sender defer: 14
2025-03-17 00:39:15,511 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-17 00:39:15,512 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: poll_exit
2025-03-17 00:39:15,517 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-17 00:39:15,519 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: server_info
2025-03-17 00:39:15,520 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: server_info
2025-03-17 00:39:15,523 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: get_summary
2025-03-17 00:39:15,523 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: sampled_history
2025-03-17 00:39:15,524 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: job_info
2025-03-17 00:39:15,784 DEBUG   SenderThread:30328 [sender.py:send_request():409] send_request: job_info
2025-03-17 00:39:15,786 DEBUG   HandlerThread:30328 [handler.py:handle_request():146] handle_request: shutdown
2025-03-17 00:39:15,786 INFO    HandlerThread:30328 [handler.py:finish():866] shutting down handler
2025-03-17 00:39:16,537 INFO    WriterThread:30328 [datastore.py:close():294] close: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250317_003459-qh0l59uo\run-qh0l59uo.wandb
2025-03-17 00:39:16,788 INFO    SenderThread:30328 [sender.py:finish():1548] shutting down sender
2025-03-17 00:39:16,788 INFO    SenderThread:30328 [file_pusher.py:finish():175] shutting down file pusher
2025-03-17 00:39:16,789 INFO    SenderThread:30328 [file_pusher.py:join():181] waiting for file pusher
